'use strict';

const path = require('path');

// ─────────────────────────────────────────────────────────────────────────────
//  CAMERA / TIMESTAMP DETECTION
//  Files auto-generated by phones/cameras must never be renamed.
//    VID_20190624_191055, IMG_20210101_120000, DCIM_001, DSC_0001,
//    20190624_191055, 2019-06-24_19-10-55
// ─────────────────────────────────────────────────────────────────────────────

const CAMERA_PREFIX_RE = /^(?:VID|IMG|DCIM|DSC|PIC|MOV|MVI|P|GOPR|GX|DJI)_\d{4,}/i;
const TIMESTAMP_PREFIX_RE = /^\d{8}[_-]\d{6}/;

function isCameraFile(filename) {
  // Strip leading bracket content like "[Drive\Google Photos] VID_..."
  // before testing so prefixed camera files are also caught
  let base = path.basename(filename, path.extname(filename));
  base = base.replace(/^\[[^\]]*\]\s*/, '').trim();
  return CAMERA_PREFIX_RE.test(base) || TIMESTAMP_PREFIX_RE.test(base);
}

module.exports = { isCameraFile, CAMERA_PREFIX_RE, TIMESTAMP_PREFIX_RE };
